collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

baseurl: "/XuHaoNB.github.io"  # 将此项设置为你的 GitHub 仓库名
url: "https://github.com/wysaly/XuHaoNB.github.io"

collections:
  authors:
    output: true
